#index:
#    path: /
#    controller: App\Controller\DefaultController::index

search:
    path: /api/v1/search
    controller: App\Controller\ApiController::search
recipes:
    path: /api/v1/recipes/{page}
    controller: App\Controller\ApiController::recipes